num1=int(input("enter your value1: "))
num2=int(input("enter your value2: "))
print("arithmetic operation values --->")
print("addition operator (num1+num2) : ",num1+num2)
print("subraction operator (num1-num2) : ",num1-num2)
print("multiplication operator (num1*num2) : ",num1*num2)
print("division operator (num1/num2) : ",num1/num2)
print("integer division operator (num1//num2) : ",num1//num2)
print("modulus operator (num1%num2) : ",num1%num2)
print("exponential operator (num1**num2) : ",num1**num2)
