def keywordargs(p,q,r,s,l=100,*pargs,**kwargs):
    print("p value = ",p)
    print("q value = ",q)
    print("r value = ",r)
    print("s value = ",s)
    print("l value = ",l)
    print(" Positional arguments values = ",pargs)
    print("Keyword arguments values =",kwargs)
    return (p,q,r,s,pargs,kwargs)
keywordargs(10,20,30,40,1000,99,88,77,a=1,b=2,c=3,d=4,e=5,f=6)