num1=int(input("Enter your value1: "))
num2=int(input("Enter your value2: "))
print("Arithmetic operator")
print("Addition (num1+num2) : ",num1+num2)
print("Subraction (num1-num2) : ",num1-num2)
print("Multiplication (num1*num2) : ",num1*num2)
print("Division (num1/num2) : ",num1/num2)
print("Integer division (num1//num2) : ",num1//num2)
print("Modulus (num1%num2) : ",num1%num2)
print("Exponential (num1**num2) : ",num1**num2)
