val1=int(input("enter your value1: "))
val2=int(input("enter your value2: "))
print("comparision operation values --->")
print("equality operator (val1==val2) : ",val1==val2)
print("inequality operator (val1!=val2) : ",val1!=val2)
print("greater than operator (val1>val2) : ",val1>val2)
print("less than operator (val1<val2) : ",val1<val2)
print("greater than or equal to operator (val1>=val2) : ",val1>=val2)
print("less than or equal to operator (val1<=val2) : ",val1<=val2)
print("(is) operator (val1 is val2) : ",val1 is val2)