val1=int(input("Enter your value1: "))
val2=int(input("Enter your value2: "))
print("Comparision operation values")
print("Equality (val1==val2) : ",val1==val2)
print("Inequality (val1!=val2) : ",val1!=val2)
print("Greater than (val1>val2) : ",val1>val2)
print("Less than (val1<val2) : ",val1<val2)
print("Greater than or equal to (val1>=val2) : ",val1>=val2)
print("Less than or equal to (val1<=val2) : ",val1<=val2)
print(" is (val1 is val2) : ",val1 is val2)